### ISSUE TITLE
some issues on 1.20.1

### ISSUE THREAD

**Issue by LordGriefington** [xanthian/variant_bookshelves#10]
1st the bookshelfs have no textures
![variantbookshelf](https://github.com/xanthian/variant_bookshelves/assets/83673600/7fc4031d-1fca-4b9c-857b-914c96dc66da)
2nd the names are using strings
![variantbookshelf2](https://github.com/xanthian/variant_bookshelves/assets/83673600/304c0e9b-9a12-4845-ba89-ea17a71bd398)
3rd items are not craftable

**Comment by xanthian** [comment]
:O 

what on earth.

**Comment by xanthian** [comment]
i see why, fix will be uploaded now. so sorry!
