### ISSUE TITLE
[2.1.5] Language file in mod breaks console log output - menu.preparingSpawn

### ISSUE THREAD

**Issue by TigerWalts** [xanthian/variant_bookshelves#12]
The mod file contains an `assets/minecraft/lang/en_us.json` file which ends up replacing the vanilla Minecraft language file. - It is not merged.

This means that all the logging format strings are missing and you end up with just the format string's id being logged.

A quick workaround is to remove that file from the Jar.

---

For linux users you can quickly identify mods that have this file with:

```bash
for f in *.jar; do unzip -l $f | grep -q assets/minecraft/lang/en_us.json && echo $f; done
```

You can remove the file with:

```bash
zip -d <jar_file> assets/minecraft/lang/en_us.json
```

**Comment by xanthian** [comment]
I'll push an update to fix this now.
thanks and apologies

**Comment by xanthian** [comment]
done
https://legacy.curseforge.com/minecraft/mc-mods/variant-bookshelves-fabric/files/4757286
