### ISSUE TITLE
[Suggestion] One creative mode tab for all variant mods.

### ISSUE THREAD

**Issue by JENOVAAbsolute** [xanthian/variant_bookshelves#3]
I need these mods as a creative builder, but I feel as if each individual mod does not add enough to warrant having their own creative tab, and it keeps me from downloading all of them. Are you willing to have one creative tab for all your variant mods? It'll definitely help reduce clutter for large amounts of creative mods.

**Comment by xanthian** [comment]
I'm not even sure that's possible unless the mods are merged, which I'd prefer not to do.
I can look in to it though

**Comment by JENOVAAbsolute** [comment]
I don't see why it wouldn't be possible. You added the BetterNether Bookshelves into the BetterNether creative tab without having to merge the mods. I don't know modding like you do though. Regardless, I wish you luck, and you have my thanks.

**Comment by xanthian** [comment]
I didnt add them, they are part of betternether, i disable mine when BN is present 😛

**Comment by xanthian** [comment]
so the only way to do this is create a separate 'library mod' that all the mods would use a static field in to register the creative tab.
which I'm not prepared to do at this time.
creating extra library mods users have to download is not something I'm willing to do.
I try to keep my mods library free (apart from FAPI).

I'm regularly updating these 'variant' mods with new blocks and have a list of ones I want to do to get them on parity with the crafting table mod at least.
if you know of any that i've missed do let me know.

**Comment by JENOVAAbsolute** [comment]
I see. Thank you anyway.
