### ISSUE TITLE
[Mod Compat Suggestion] Colorful Azaleas

### ISSUE THREAD

**Issue by BreadBxsket** [xanthian/variant_bookshelves#4]
https://www.curseforge.com/minecraft/mc-mods/colorfulazaleas

Adds 7 azalea tree variants

**Comment by xanthian** [comment]
Excellent :) been looking for another mod compat to do :)

**Comment by xanthian** [comment]
done :)
https://github.com/xanthian/variant_bookshelves/commit/adbc2d1a95d18a0521a0b60ca5ce9c72ebc22f34
will be on CF shortly.
