### ISSUE TITLE
[Suggestion] 3D Textures

### ISSUE THREAD

**Issue by WiredSamurai** [xanthian/variant_bookshelves#5]
3D Versions at some point in the Future across all of your Variant mods? Or are they compatible with 3D Resource Packs/Mods? Either way it'd be super cool to have 3D Versions.

**Comment by xanthian** [comment]
You'd have to show me an example because im not sure what you mean.

**Comment by WiredSamurai** [comment]
This is from the Vanilla Tweaks Resource pack. ![3DBookshelves](https://user-images.githubusercontent.com/70826190/203029196-fc274cc4-e14a-41a0-a6a6-242cc283fa1f.png)

**Comment by xanthian** [comment]
Hmm, interesting.
Looks much better, will take a look at this.

**Comment by xanthian** [comment]
![image](https://user-images.githubusercontent.com/7688001/203156209-214d9676-34d4-4685-b3ba-ed1c282792de.png)

Seems easy enough to do, although somewhat long winded.
May do it as an optional texture pack.

**Comment by WiredSamurai** [comment]
If there is any way I can possibly help you, let me know. Not sure what program you use to do texturing but I am more than willing to try and help if wanted. It looks really good!
