### ISSUE TITLE
zh_cn.json

### ISSUE THREAD

**Issue by DarkCrystalll** [xanthian/variant_bookshelves#6]
{
  "itemGroup.variant_bookshelves.variant_bookshelves" : "Variant书架",

  "_vanilla": "Vanilla书架",
  "block.minecraft.bookshelf": "橡木书架",
    "block.variant_bookshelves.block.acacia_bookshelf": "金合欢书架",
  "block.variant_bookshelves.block.birch_bookshelf": "白桦木书架",
  "block.variant_bookshelves.block.dark_oak_bookshelf": "深色橡木书架",
  "block.variant_bookshelves.block.jungle_bookshelf": "丛林木书架",
  "block.variant_bookshelves.block.mangrove_bookshelf": "红树木书架",
  "block.variant_bookshelves.block.spruce_bookshelf": "云杉木书架",
  "block.variant_bookshelves.block.crimson_bookshelf": "深红书架",
  "block.variant_bookshelves.block.warped_bookshelf": "诡异书架",

  "block.variant_bookshelves.block.rubber_bookshelf": "橡胶木书架",

  "block.variant_bookshelves.block.azalea_bookshelf": "杜鹃花书架",
  "block.variant_bookshelves.block.coconut_bookshelf": "椰子书架",
  "block.variant_bookshelves.block.flowering_azalea_bookshelf": "盛开的杜鹃花书架",
  "block.variant_bookshelves.block.walnut_bookshelf": "核桃书架",
  "block.variant_bookshelves.block.cinnamon_bookshelf": "肉桂书架",

  "block.variant_bookshelves.block.jade_bookshelf": "翡翠白桦木书架",
  "block.variant_bookshelves.block.moon_bookshelf": "月亮书架",
  "block.variant_bookshelves.block.shadow_bookshelf": "影子书架",

  "block.variant_bookshelves.block.mango_bookshelf": "芒果书架",

  "block.variant_bookshelves.block.fir_bookshelf": "冷杉书架",

  "block.variant_bookshelves.block.cypress_bookshelf": "柏树书架",
  "block.variant_bookshelves.block.hemlock_bookshelf": "毒芹书架",
  "block.variant_bookshelves.block.japanese_maple_bookshelf": "日本枫树书架",
  "block.variant_bookshelves.block.rainbow_eucalyptus_bookshelf": "彩虹桉树书架",
  "block.variant_bookshelves.block.redwood_bookshelf": "红木书架",
  "block.variant_bookshelves.block.rubber_bookshelf2": "橡胶书架",
  "block.variant_bookshelves.block.sakura_bookshelf": "樱花书架",
  "block.variant_bookshelves.block.willow_bookshelf": "柳树书架",
  "block.variant_bookshelves.block.yucca_palm_bookshelf": "丝兰棕榈书架",

  "block.variant_bookshelves.block.scorched_bookshelf": "烧焦书架",
  "block.variant_bookshelves.block.umbral_bookshelf": "雨伞书架",

  "block.variant_bookshelves.block.bamboo_bookshelf": "竹子书架",
  "block.variant_bookshelves.block.charred_bookshelf": "烧焦书架",
  "block.variant_bookshelves.block.herringbone_acacia_bookshelf": "人字形金合欢书架",
  "block.variant_bookshelves.block.herringbone_bamboo_bookshelf": "人字形竹子书架",
  "block.variant_bookshelves.block.herringbone_birch_bookshelf": "人字形白桦木书架",
  "block.variant_bookshelves.block.herringbone_charred_bookshelf": "人字形烧焦书架",
  "block.variant_bookshelves.block.herringbone_crimson_bookshelf": "人字形深红书架",
  "block.variant_bookshelves.block.herringbone_dark_oak_bookshelf": "人字形深色橡木书架",
  "block.variant_bookshelves.block.herringbone_jungle_bookshelf": "人字形丛林木书架",
  "block.variant_bookshelves.block.herringbone_mangrove_bookshelf": "人字形红树木书架",
  "block.variant_bookshelves.block.herringbone_oak_bookshelf": "人字形橡木书架",
  "block.variant_bookshelves.block.herringbone_spruce_bookshelf": "人字形云杉木书架",
  "block.variant_bookshelves.block.herringbone_warped_bookshelf": "人字形诡异书架",
  "block.variant_bookshelves.block.herringbone_white_oak_bookshelf": "人字形白色橡木书架",
  "block.variant_bookshelves.block.legacy_bookshelf": "传统书架",
  "block.variant_bookshelves.block.white_oak_bookshelf": "白色橡木书架",

  "block.variant_bookshelves.block.cypress_bookshelf2": "柏树书架",
  "block.variant_bookshelves.block.dragons_blood_bookshelf": "龙血书架",
  "block.variant_bookshelves.block.elder_bookshelf": "长者书架",
  "block.variant_bookshelves.block.juniper_bookshelf": "桧木书架",

  "block.variant_bookshelves.block.ancient_oak_bookshelf": "古橡木书架",
  "block.variant_bookshelves.block.blighted_balsa_bookshelf": "枯萎的轻木书架",
  "block.variant_bookshelves.block.swamp_cypress_bookshelf": "沼泽柏树书架",
  "block.variant_bookshelves.block.willow_bookshelf2": "柳树书架",

  "block.variant_bookshelves.block.dreamwood_bookshelf": "梦木书架",
  "block.variant_bookshelves.block.livingwood_bookshelf": "活木书架",
  "block.variant_bookshelves.block.mossy_dreamwood_bookshelf": "苔藓梦木书架",
  "block.variant_bookshelves.block.mossy_livingwood_bookshelf": "苔藓活木书架",
  "block.variant_bookshelves.block.shimmerwood_bookshelf": "微光木书架",

  "block.variant_bookshelves.block.cherry_oak_bookshelf": "樱桃橡木书架",
  "block.variant_bookshelves.block.dark_amaranth_bookshelf": "深色苋菜书架",
  "block.variant_bookshelves.block.palm_bookshelf": "棕榈书架",

  "block.variant_bookshelves.block.black_bookshelf": "黑色书架",
  "block.variant_bookshelves.block.blue_bookshelf": "蓝色书架",
  "block.variant_bookshelves.block.brown_bookshelf": "棕色书架",
  "block.variant_bookshelves.block.cyan_bookshelf": "青色书架",
  "block.variant_bookshelves.block.gray_bookshelf": "灰色书架",
  "block.variant_bookshelves.block.green_bookshelf": "绿色书架",
  "block.variant_bookshelves.block.light_blue_bookshelf": "淡蓝色书架",
  "block.variant_bookshelves.block.light_gray_bookshelf": "淡灰色书架",
  "block.variant_bookshelves.block.lime_bookshelf": "黄绿色书架",
  "block.variant_bookshelves.block.magenta_bookshelf": "品红色书架",
  "block.variant_bookshelves.block.orange_bookshelf": "橙色书架",
  "block.variant_bookshelves.block.pink_bookshelf": "粉色书架",
  "block.variant_bookshelves.block.purple_bookshelf": "紫色书架",
  "block.variant_bookshelves.block.red_bookshelf": "红色书架",
  "block.variant_bookshelves.block.white_bookshelf": "白色书架",
  "block.variant_bookshelves.block.yellow_bookshelf": "黄色书架",

  "block.variant_bookshelves.block.wisteria_bookshelf": "紫藤书架",

  "block.variant_bookshelves.block.bamboo_bookshelf2": "竹子书架",
  "block.variant_bookshelves.block.redwood_bookshelf2": "红木书架",

  "block.variant_bookshelves.block.stripped_bamboo_bookshelf": "剥离竹子书架",

  "block.variant_bookshelves.block.crystal_bookshelf": "水晶书架",
  "block.variant_bookshelves.block.golden_oak_bookshelf": "金橡木书架",
  "block.variant_bookshelves.block.orange_bookshelf2": "橙色书架",
  "block.variant_bookshelves.block.skyroot_bookshelf": "天空根书架",
  "block.variant_bookshelves.block.wisteria_bookshelf2": "紫藤书架",

  "block.variant_bookshelves.block.azule_azalea_bookshelf": "青金杜鹃花书架",
  "block.variant_bookshelves.block.bright_azalea_bookshelf": "闪耀杜鹃花书架",
  "block.variant_bookshelves.block.fiss_azalea_bookshelf": "Fiss杜鹃花书架",
  "block.variant_bookshelves.block.roze_azalea_bookshelf": "Roze杜鹃花书架",
  "block.variant_bookshelves.block.tecal_azalea_bookshelf": "Tecal杜鹃花书架",
  "block.variant_bookshelves.block.titanium_azalea_bookshelf": "Titanium杜鹃花书架",
  "block.variant_bookshelves.block.walnut_azalea_bookshelf": "Walnut杜鹃花书架",

  "block.variant_bookshelves.block.baobab_bookshelf": "猴面包书架",
  "block.variant_bookshelves.block.cypress_bookshelf3": "柏木书架"
}

**Comment by xanthian** [comment]
many thanks, have added this to 1.19.3 release
will back port when I update.
