### ISSUE TITLE
[Mod Compat] Update Paradise Lost Compat

### ISSUE THREAD

**Issue by kingkuys2123** [xanthian/variant_bookshelves#8]
Paradise lost had a huge update, they removed **Crystal Wood** 
and renamed then re-sprite the rest of the woods except the Orange Wood

**Renamed and Re-sprited Woods:**
- Skyroot -> Aurel
- Golden Oak -> Mother Aurel

**Removed Wood:**
- Crystal 

[**Paradise Lost Recent Update Changelog**](https://www.curseforge.com/minecraft/mc-mods/paradise-lost/files/4379294)

**Comment by xanthian** [comment]
Will be added in 1.2.5 going up on CF shortly
