### ISSUE TITLE
[Bug] Spruce bookshelves not leveling enchanting table.

### ISSUE THREAD

**Issue by jonask028** [xanthian/variant_bookshelves#9]
Default bookshelves do, haven't tested any others.

**Comment by NNJAShadowz** [comment]
Are you using the mod EasyMagic? Seems like these two mods don't work together.

**Comment by SplendidAlakey** [comment]
Yep, Easy Magic compatibility issue, but the fix is super easy, VB just needs to add their shelves to the common bookshelves tag: https://github.com/Fuzss/easymagic/issues/29#issuecomment-1522814284

Tried it myself and it works.

**Comment by xanthian** [comment]
![image](https://user-images.githubusercontent.com/7688001/236623314-e6d23a44-eb5f-47a1-a3d9-13c18d4a1c16.png)

Should be fixed in 1.2.5 going on CF shortly, apologies for the delay
